In [26]:
import os
from natsort import natsorted
import numpy as np

In [23]:
root= 'data'

all_path = []
all_months = []


all_months = os.listdir(root)    
all_months = natsorted(all_months)
print(all_months)

['aqx_p_13_2020-01', 'aqx_p_13_2020-02', 'aqx_p_13_2020-03', 'aqx_p_13_2020-04', 'aqx_p_13_2020-05', 'aqx_p_13_2020-06', 'aqx_p_13_2020-07', 'aqx_p_13_2020-08', 'aqx_p_13_2020-09', 'aqx_p_13_2020-10', 'aqx_p_13_2020-11']


In [24]:
os.path.join(root, all_months[0])

'data/aqx_p_13_2020-01'

In [21]:
for each_month in all_months:
    all_days = []
    month_path = os.path.join(root, each_month)
    for each_day in os.listdir(month_path):
        all_days.append(each_day)
        
    all_days = natsorted(all_days)
    for each_day in all_days:
        day_path = os.path.join(month_path, each_day)
        
        print(day_path)
        all_path.append(day_path)

data/aqx_p_13_2020-01/aqx_p_13_2020-01-01.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-02.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-03.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-04.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-05.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-06.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-07.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-08.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-09.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-10.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-11.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-12.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-13.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-14.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-15.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-16.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-17.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-18.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-19.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-20.csv
data/aqx_p_13_2020-01/aqx_p_13_2020-01-21.csv
data/aqx_p_13_2020-01/aqx_p_13_202

In [6]:
os.listdir(root)


['aqx_p_13_2020-08',
 'aqx_p_13_2020-01',
 'aqx_p_13_2020-04',
 'aqx_p_13_2020-02',
 'aqx_p_13_2020-09',
 'aqx_p_13_2020-07',
 'aqx_p_13_2020-06',
 'aqx_p_13_2020-10',
 'aqx_p_13_2020-03',
 'aqx_p_13_2020-11',
 'aqx_p_13_2020-05']

In [7]:
all_months

['aqx_p_13_2020-08',
 'aqx_p_13_2020-01',
 'aqx_p_13_2020-04',
 'aqx_p_13_2020-02',
 'aqx_p_13_2020-09',
 'aqx_p_13_2020-07',
 'aqx_p_13_2020-06',
 'aqx_p_13_2020-10',
 'aqx_p_13_2020-03',
 'aqx_p_13_2020-11',
 'aqx_p_13_2020-05']

In [9]:
all_files = []
from os import walk
for root, dirs, files in walk('data'):
    for f in files:
        all_files.append(f)
#         pd.read_csv(f)#一次讀一個file

print(all_files)

['aqx_p_13_2020-08-05.csv', 'aqx_p_13_2020-08-24.csv', 'aqx_p_13_2020-08-31.csv', 'aqx_p_13_2020-08-01.csv', 'aqx_p_13_2020-08-11.csv', 'aqx_p_13_2020-08-20.csv', 'aqx_p_13_2020-08-18.csv', 'aqx_p_13_2020-08-09.csv', 'aqx_p_13_2020-08-22.csv', 'aqx_p_13_2020-08-13.csv', 'aqx_p_13_2020-08-27.csv', 'aqx_p_13_2020-08-30.csv', 'aqx_p_13_2020-08-16.csv', 'aqx_p_13_2020-08-02.csv', 'aqx_p_13_2020-08-10.csv', 'aqx_p_13_2020-08-29.csv', 'aqx_p_13_2020-08-15.csv', 'aqx_p_13_2020-08-07.csv', 'aqx_p_13_2020-08-03.csv', 'aqx_p_13_2020-08-06.csv', 'aqx_p_13_2020-08-21.csv', 'aqx_p_13_2020-08-26.csv', 'aqx_p_13_2020-08-25.csv', 'aqx_p_13_2020-08-12.csv', 'aqx_p_13_2020-08-28.csv', 'aqx_p_13_2020-08-17.csv', 'aqx_p_13_2020-08-14.csv', 'aqx_p_13_2020-08-19.csv', 'aqx_p_13_2020-08-08.csv', 'aqx_p_13_2020-08-23.csv', 'aqx_p_13_2020-08-04.csv', 'aqx_p_13_2020-01-08.csv', 'aqx_p_13_2020-01-25.csv', 'aqx_p_13_2020-01-13.csv', 'aqx_p_13_2020-01-20.csv', 'aqx_p_13_2020-01-22.csv', 'aqx_p_13_2020-01-16.csv', 

In [37]:
array = np.random.randint(5,60,10)
print(array)

[11 56 40 56 12 14 35 32 12 43]


In [38]:
new_array = np.where(array>30) # output idx
print(new_array)

(array([1, 2, 3, 6, 7, 9]),)


In [39]:
array[array > 30]

array([56, 40, 56, 35, 32, 43])